### ISSUE TITLE
how did you know the control id

### ISSUE THREAD

**Issue by huangshangbin** [sergeylukin/mql4-auth#1]
like line91  e=GetDlgItem(h,0x49d); the id number 0x49d how to find it

**Comment by sergeylukin** [comment]
Wow, sorry for astronomic delay, just noticed your question now by randomly revisiting this project. To answer your question - I've used https://web.archive.org/web/20090916053057/http://www.windows-spy.com/ or you could use any tool that has similar  functionality https://alternativeto.net/software/spy--/

Hope that helps :)
